---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation - Hardening
# Linux OS for Servers (3.65)
# Tasks: 04 IPTables
# ------------------------------------------------------------------------

# Req 48:	If iptables is used, policies for loopback traffic must be configured.

- name: req-048.1 configure loopback traffic input rule
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  when: config_iptables_loopback and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

- name: req-048.2 configure loopback traffic output rule
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
  when: config_iptables_loopback and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

- name: req-048.3 configure loopback traffic drop rule
  iptables:
    chain: INPUT
    source: 127.0.0.0/8
    jump: DROP
  when: config_iptables_loopback and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

# Req 49:	If iptables is used, policies for outbound and established connections
# must be configured.

- name: req-049.1 configure outbound connections
  iptables:
    chain: OUTPUT
    protocol: '{{ item }}'
    match: state
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  with_items:
    - 'tcp'
    - 'udp'
    - 'icmp'
  when: config_iptables_outbound and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

- name: req-049.2 configure inbound connections
  iptables:
    chain: INPUT
    protocol: '{{ item }}'
    match: state
    ctstate: ESTABLISHED
    jump: ACCEPT
  with_items:
    - 'tcp'
    - 'udp'
    - 'icmp'
  when: config_iptables_outbound and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

# Req 50:	If iptables is used, policies must exist for all ports in listening
# state.

- name: req-050.1 configure rules for tcp
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    match: state
    ctstate: NEW
    jump: ACCEPT
  with_items: "{{ tcp_services }}"
  when: config_iptables_rules_tcp|bool

- name: req-050.2 configure rules for udp
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "{{ item }}"
    match: state
    ctstate: NEW
    jump: ACCEPT
  with_items: "{{ udp_services }}"
  when: config_iptables_rules_udp|bool

- name: req-050.3 configure rules for icmp (ping)
  iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: 8
    match: state
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
  when: config_iptables_rules_icmp_ping and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )

# Req 51:	If iptables is used, the default policy must be configured to drop all
# traffic.

- name: req-006.0 configure default deny policies
  iptables:
    chain: '{{ item }}'
    policy: DROP
  with_items:
    - 'INPUT'
    - 'OUTPUT'
    - 'FORWARD'
  when: config_iptables_default_policy and
      ( config_iptables_rules_tcp or config_iptables_rules_udp )
